### PR TITLE
bugfix/logical-type

### LINKED ISSUE #579: Merge command doesn't work?
Trying to run `merge` on the same parquet file fails for me. I can create an example to repro if needed. Currently I downloaded from source (go install). I will look into the issue a bit myself

### PR DESCRIPTION
**Pull request by AnthonyHewins**
Logical type was being compared by a pointer deref, but should be compared using the `Equals` operator

Closes #579

### CODE REVIEW

File: cmd/merge.go [hunk 1]
```diff
@@ -92,7 +92,7 @@ func (c MergeCmd) openSources() ([]*reader.ParquetReader, *pschema.SchemaNode, e
 		if schema == nil {
 			schema = currSchema
 		} else if !schema.Equals(*currSchema) {
-			return nil, nil, fmt.Errorf("[%s] does not have same schema as previous files", source)
+			return nil, nil, fmt.Errorf("[%s] does not have same schema as previous files.Want: %v\nGot: %v", source, schema, *currSchema)
```
Comment (AnthonyHewins) [inline cmd/merge.go:95]: This was to help me debug. Lmk if you want removed

File: cmd/merge_test.go [hunk 2]
```diff
@@ -69,7 +71,7 @@ func Test_MergeCmd_Run_good(t *testing.T) {
 
 			reader, _ := pio.NewParquetFileReader(tc.cmd.URI, rOpt)
 			rowCount := reader.GetNumRows()
-			require.Equal(t, rowCount, tc.rowCount)
+			require.Equal(t, tc.rowCount, rowCount)
```
Comment (AnthonyHewins) [inline cmd/merge_test.go:74]: Seems expected and actual were swapped here

File: testdata/random-example1.parquet
Comment (AnthonyHewins) [inline testdata/random-example1.parquet:1]: Bin files here include the schema that failed that caused me to open the ticket #579 i included them as test cases

File: internal/schema/schemanode.go [hunk 3]
```diff
@@ -396,7 +393,7 @@ func schemaElementEquals(s, v parquet.SchemaElement) bool {
 		equals(s.Scale, v.Scale) &&
 		equals(s.Precision, v.Precision) &&
 		equals(s.FieldID, v.FieldID) &&
-		equals(s.LogicalType, v.LogicalType)
+		s.LogicalType.Equals(v.LogicalType)
```
Comment (AnthonyHewins) [inline internal/schema/schemanode.go:396]: This has `nil` checks built in

File: cmd/merge_test.go [hunk 4]
```diff
@@ -49,9 +49,11 @@ func Test_MergeCmd_Run_good(t *testing.T) {
 		cmd      MergeCmd
 		rowCount int64
 	}{
-		"good":    {MergeCmd{rOpt, wOpt, 10, []string{"good.parquet", "good.parquet"}, "", false}, 6},
-		"empty":   {MergeCmd{rOpt, wOpt, 10, []string{"empty.parquet", "empty.parquet"}, "", false}, 0},
-		"top-tag": {MergeCmd{rOpt, wOpt, 10, []string{"top-level-tag1.parquet", "top-level-tag2.parquet"}, "", false}, 6},
+		"good":                    {MergeCmd{rOpt, wOpt, 10, []string{"good.parquet", "good.parquet"}, "", false}, 6},
+		"random-example-repeated": {MergeCmd{rOpt, wOpt, 10, []string{"random-example1.parquet", "random-example1.parquet"}, "", false}, 54},
```
Comment (hangxie) [inline cmd/merge_test.go:53]: Would you please use `all-types.parquet` instead? or if you really want to use `random-example1.parquet`, please help to add a small program to generate this test data, there are quite some examples under https://github.com/hangxie/parquet-tools/tree/main/testdata/gen.

File: internal/schema/schemanode.go (hunk 3 above)
Comment (hangxie) [reply internal/schema/schemanode.go:396]: This is neat, I didn't realize that there is such a function already 😭

File: testdata/random-example1.parquet
Comment (hangxie) [reply testdata/random-example1.parquet:1]: Check comment above, probably don't need this if all-types.parquet can serve the same purpose.

File: internal/schema/schemanode.go (hunk 3 above)
Comment (hangxie) [reply internal/schema/schemanode.go:396]: > This has nil checks built in

If LogicalType is nil ...

File: cmd/merge_test.go (hunk 4 above)
Comment (AnthonyHewins) [reply cmd/merge_test.go:53]: Yep all tpyes works that triggered the test case

File: internal/schema/schemanode.go (hunk 3 above)
Comment (AnthonyHewins) [reply internal/schema/schemanode.go:396]: > > This has nil checks built in
> 
> If LogicalType is nil ...

So it should still be good. I had to check my Go fundamentals again, but as long as the `nil` is typed, the runtime takes care of it. Here's the code under the hood:

```go
func (p *LogicalType) Equals(other *LogicalType) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
```

Ok good, so it catches nils. So i didnt want to commit an extra nil check for no reason. Here's a playground link i did to check myself: https://go.dev/play/p/_HuAyiIB4Hy so i think we're good here?

**Comment by AnthonyHewins** [comment]
I have one test case failing locally that seems to be network related in the `io` package. I think I saw in your commit history somewhere that this is rolled back or expected so I'll just leave it

>                 Error:          "unable to open file [https://no-such-host.tld/]: Get \"https://no-such-host.tld/\": dial tcp 143.244.220.150:443: i/o timeout" does not contain "no such host"

**Review by hangxie — APPROVED** [review]
👍

**Comment by hangxie** [comment]
> I have one test case failing locally that seems to be network related in the `io` package. I think I saw in your commit history somewhere that this is rolled back or expected so I'll just leave it

Some ISPs use "catch-all" DNS server, which is more like a domain hijack to me but that's the life ... I will let it go as long as CI passes.

**Comment by hangxie** [comment]
ehh one more thing, do you mind signing your commit? I can bypass the rule if you don't want to though ...

I should have it in GHA, will do it later though.
